### ISSUE TITLE
 Hello, I would like to collaborate with your code. I do not see the sql file.

### ISSUE THREAD

**Issue by developerccs** [Piyushhbhutoria/FinTech#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by developerccs** [comment]
Hello, I would like to collaborate with your code. I do not see the sql file.

**Comment by Piyushhbhutoria** [comment]
Thanks for your offer, I would like to take the project further reach me at Piyush.bhutoria98@gmail.com for the sql file. lets get going.

**Comment by Piyushhbhutoria** [comment]
sql file is uploaded in the [database](/database) folder.
